config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :tweets do
    resources :comments
  end
  get '/search', to: 'tweets#search'
  post '/retweet', to: 'tweets#retweet'
  root to: "tweets#index"
end

app/models/comment.rb
class Comment
  include Mongoid::Document
  field :title, type: String
  field :description, type: String
  field :created_at, type: Time
  field :updated_at, type: Time
  belongs_to :user
  belongs_to :tweet
end

app/models/tweet.rb
class Tweet
  include Mongoid::Document
  field :description, type: String
  field :created_at, type: Time
  field :updated_at, type: Time
  belongs_to :user
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  # field :sign_in_count,      type: Integer, default: 0
  # field :current_sign_in_at, type: Time
  # field :last_sign_in_at,    type: Time
  # field :current_sign_in_ip, type: String
  # field :last_sign_in_ip,    type: String

  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time
  has_many :tweets, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_comment, only: %i[ show edit update destroy ]

  # POST /comments or /comments.json
   def create
      @tweet   = Tweet.find(params[:tweet_id])
      @comment = @tweet.comments.create(comment_params)
      redirect_to tweet_path(@tweet)
    end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:title, :description, :created_at, :updated_at, :user_id, :tweet_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
  end
  
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!, only: %i[create update retweet destroy]
  before_action :set_tweet, only: %i[ show edit update retweet destroy ]

  # GET /tweets or /tweets.json
  def index
    @tweets = Tweet.all
  end

  # GET /tweets/1 or /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets or /tweets.json
  def create
    create_tweet_params = tweet_params
    create_tweet_params[:created_at] = Date.current.to_time.to_datetime
    @tweet = current_user.tweets.new(create_tweet_params)
    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: "Tweet was successfully created." }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1 or /tweets/1.json
  def update
    update_tweet_params = tweet_params
    update_tweet_params[:created_at] = @tweet.created_at
    update_tweet_params[:updated_at] = Date.current.to_time.to_datetime
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: "Tweet was successfully updated." }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1 or /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: "Tweet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def search
    @tweets = Tweet.any_of({description: /#{params[:search_term]}/}).entries
  end

  def retweet
    retweet_params = {description: @tweet.description, created_at: @tweet.created_at, updated_at: @tweet.updated_at}
    @tweet         = current_user.tweets.new(retweet_params)
    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: "Tweet was successfully created." }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:description, :created_at, :updated_at, :user_id, :search_term)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/home/index.html.erb
<p>Home Index</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twitter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Twitter</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav" style="margin-left: auto;">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: "nav-link"%>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign in", new_user_session_path, class: "nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "Register", new_user_registration_path, class: "nav-link"%>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/tweets/_form.html.erb
<%= form_with(model: tweet) do |form| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
        <% tweet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :created_at %>
    <%= form.datetime_select :created_at %>
  </div>

  <div class="field">
    <%= form.label :updated_at %>
    <%= form.datetime_select :updated_at %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tweets</h1>

<%= form_with(url: search_path, method: "get", local: true) do %>
  <%= label_tag(:location, "Search Tweet:") %>
  <%= text_field_tag(:search_term) %>
  <%= submit_tag("Search") %>
<% end %>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Created at</th>
      <th>Updated at</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tweets.each do |tweet| %>
      <tr>
        <td><%= tweet.description %></td>
        <td><%= tweet.created_at %></td>
        <td><%= tweet.updated_at %></td>
        <% if tweet.user_id.present? %>
          <td><%= tweet.user.email %></td>
        <% else %>
          <td><%= tweet.user_id %></td>
        <% end %>
        <td><%= link_to 'Show', tweet %></td>
        <% if user_signed_in?%>
          <td><%= link_to "Retweet", retweet_path(id: tweet.id), method: :post %></td>
          <%if current_user && current_user.id == tweet.user_id%>
            <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
            <td><%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tweet', new_tweet_path %>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/search.html.erb
<h1>Tweets</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Created at</th>
      <th>Updated at</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tweets.each do |tweet| %>
      <tr>
        <td><%= tweet.description %></td>
        <td><%= tweet.created_at %></td>
        <td><%= tweet.updated_at %></td>
        <td><%= tweet.user_id %></td>
        <td><%= link_to 'Show', tweet %></td>
        <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
        <td><%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'List all Tweet', tweets_path %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @tweet.description %>
</p>

<p>
  <strong>Created at:</strong>
  <%= @tweet.created_at %>
</p>

<p>
  <strong>Updated at:</strong>
  <%= @tweet.updated_at %>
</p>

<p>
  <strong>User:</strong>
  <%= @tweet.user_id %>
</p>

<h2>Comments</h2>
<% if @tweet && @tweet.comments %>
  <% @tweet.comments.each do |comment| %>
    <p>
      <strong>Commenter:</strong>
      <%= comment.user.email %>
    </p>

    <p>
      <strong>Title:</strong>
      <%= comment.title %>
    </p>

    <p>
      <strong>Description:</strong>
      <%= comment.description %>
    </p>
  <% end %>
<% end %>

<% if user_signed_in? %>

  <h2>Add a comment:</h2>
  <%= form_with model: [ @tweet, @tweet.comments.build ] do |form| %>
    <p>
      <%= form.label :commenter %><br>
      <%= form.text_field :user_id %>
    </p>
    <p>
      <%= form.label :title %><br>
      <%= form.text_area :title %>
    </p>
    <p>
      <%= form.label :description %><br>
      <%= form.text_area :description %>
    </p>
    <p>
      <%= form.submit %>
    </p>
  <% end %>
  <%if current_user && current_user.id == @tweet.user_id%>
    <%= link_to 'Edit', edit_tweet_path(@tweet) %> |
  <% end %>
<% end %>
<%= link_to 'Back', tweets_path %>